Repository prgrms-aibe-devcourse/AIBE3_Project2_Team1_BE, pull requests merged in 2025-10, with the labels that each got.

#20 [feat] 유저 CRUD, JWT 구현
  .env.default
  src/main/java/com/hotsix/server/admin/entity/Category.java
  src/main/java/com/hotsix/server/admin/entity/Report.java
  src/main/java/com/hotsix/server/admin/entity/Tag.java
  src/main/java/com/hotsix/server/auth/service/AuthService.java
  src/main/java/com/hotsix/server/global/Rq/Rq.java
  src/main/java/com/hotsix/server/global/config/SecurityConfig.java
  src/main/java/com/hotsix/server/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hotsix/server/global/entity/BaseEntity.java
  src/main/java/com/hotsix/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/hotsix/server/global/rsData/RsData.java
  src/main/java/com/hotsix/server/global/standard/util/Ut.java
  src/main/java/com/hotsix/server/message/entity/Message.java
  src/main/java/com/hotsix/server/message/entity/Notification.java
  src/main/java/com/hotsix/server/milestone/entity/Deliverable.java
  src/main/java/com/hotsix/server/milestone/entity/Milestone.java
  src/main/java/com/hotsix/server/profile/entity/Profile.java
  src/main/java/com/hotsix/server/project/entity/Project.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalResponseDto.java
  src/main/java/com/hotsix/server/proposal/entity/Contract.java
  src/main/java/com/hotsix/server/proposal/entity/Proposal.java
  src/main/java/com/hotsix/server/review/entity/Review.java
  src/main/java/com/hotsix/server/user/controller/UserController.java
  src/main/java/com/hotsix/server/user/dto/UserDto.java
  src/main/java/com/hotsix/server/user/dto/UserLoginRequestDto.java
  src/main/java/com/hotsix/server/user/dto/UserLoginResponseDto.java
  src/main/java/com/hotsix/server/user/dto/UserPasswordChangeRequestDto.java
  src/main/java/com/hotsix/server/user/dto/UserRegisterRequestDto.java
  src/main/java/com/hotsix/server/user/dto/UserResponseDto.java
  src/main/java/com/hotsix/server/user/dto/UserUpdateRequestDto.java
  src/main/java/com/hotsix/server/user/entity/LoginType.java
  src/main/java/com/hotsix/server/user/entity/User.java
  src/main/java/com/hotsix/server/user/exception/UserErrorCase.java
  src/main/java/com/hotsix/server/user/repository/UserRepository.java
  src/main/java/com/hotsix/server/user/service/UserService.java
  src/main/resources/application-docker.yml
  src/test/java/com/hotsix/server/redis/RedisTemplateTest.java
Labels: 💡 feature

#21 [fix] 스프링 서버 안열리는 문제 해결
  src/main/java/com/hotsix/server/proposal/controller/ProposalController.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalRequestBody.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalRequestDto.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalResponseDto.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalStatusRequestBody.java
  src/main/java/com/hotsix/server/proposal/entity/Proposal.java
  src/main/java/com/hotsix/server/proposal/entity/proposalPorfolio/ProposalFile.java
  src/main/java/com/hotsix/server/proposal/service/ProposalService.java
Labels: 🐛 bug fix

#22 [fix] 리뷰 관련 API 구현, 리뷰 도메인 로직 테스트코드 작성, BaseEntity 관련 PK 오류 해결
  .gitignore
  build.gradle
  src/main/java/com/hotsix/server/admin/entity/Category.java
  src/main/java/com/hotsix/server/admin/entity/Report.java
  src/main/java/com/hotsix/server/admin/entity/Tag.java
  src/main/java/com/hotsix/server/auth/resolver/CurrentUser.java
  src/main/java/com/hotsix/server/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/hotsix/server/auth/service/AuthService.java
  src/main/java/com/hotsix/server/global/config/WebMvcConfig.java
  src/main/java/com/hotsix/server/global/entity/BaseEntity.java
  src/main/java/com/hotsix/server/message/entity/Message.java
  src/main/java/com/hotsix/server/message/entity/Notification.java
  src/main/java/com/hotsix/server/milestone/entity/Deliverable.java
  src/main/java/com/hotsix/server/milestone/entity/Milestone.java
  src/main/java/com/hotsix/server/profile/entity/Profile.java
  src/main/java/com/hotsix/server/project/entity/Project.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalResponseDto.java
  src/main/java/com/hotsix/server/proposal/entity/Contract.java
  src/main/java/com/hotsix/server/proposal/entity/Proposal.java
  src/main/java/com/hotsix/server/proposal/entity/proposalPorfolio/ProposalFile.java
  src/main/java/com/hotsix/server/proposal/service/ProposalService.java
  src/main/java/com/hotsix/server/review/controller/ReviewController.java
  src/main/java/com/hotsix/server/review/dto/ReviewRequestDto.java
  src/main/java/com/hotsix/server/review/dto/ReviewResponseDto.java
  src/main/java/com/hotsix/server/review/entity/Review.java
  src/main/java/com/hotsix/server/review/entity/ReviewImage.java
  src/main/java/com/hotsix/server/review/exception/ReviewErrorCase.java
  src/main/java/com/hotsix/server/review/repository/ReviewImageRepository.java
  src/main/java/com/hotsix/server/review/repository/ReviewRepository.java
  src/main/java/com/hotsix/server/review/service/ReviewService.java
  src/main/java/com/hotsix/server/user/dto/UserDto.java
  src/main/java/com/hotsix/server/user/entity/User.java
  src/main/java/com/hotsix/server/user/service/UserService.java
  src/test/java/com/hotsix/server/review/controller/ReviewControllerTest.java
  src/test/java/com/hotsix/server/review/service/ReviewServiceTest.java
Labels: 💡 feature, 🤔 test, 🛠️ fix, 🐛 bug fix

#25 [test] 프로젝트 등록, 상태 변경 관련 서비스,컨트롤러 로직 테스트코드 구현
  src/test/java/com/hotsix/server/project/controller/ProjectControllerTest.java
  src/test/java/com/hotsix/server/project/service/ProjectServiceTest.java
Labels: 🤔 test

#29 [feat] 관리자 로그인, 대시보드 API 구현
  src/main/java/com/hotsix/server/admin/config/AdminAuthInterceptor.java
  src/main/java/com/hotsix/server/admin/config/AdminProperties.java
  src/main/java/com/hotsix/server/admin/controller/AdminController.java
  src/main/java/com/hotsix/server/admin/dto/AdminDashboardResponseDto.java
  src/main/java/com/hotsix/server/admin/dto/AdminLoginRequestDto.java
  src/main/java/com/hotsix/server/admin/dto/AdminRecentProjectDto.java
  src/main/java/com/hotsix/server/admin/service/AdminDashboardService.java
  src/main/java/com/hotsix/server/global/config/SecurityConfig.java
  src/main/java/com/hotsix/server/global/config/WebMvcConfig.java
  src/main/java/com/hotsix/server/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/hotsix/server/project/entity/Project.java
  src/main/java/com/hotsix/server/project/repository/ProjectRepository.java
  src/main/java/com/hotsix/server/project/service/ProjectService.java
  src/main/java/com/hotsix/server/review/repository/ReviewRepository.java
  src/main/java/com/hotsix/server/user/repository/UserRepository.java
Labels: 💡 feature, 🔧 refactor

#34 [fix] 제안서 등록 시 파일 등록기능 제거 및 유저 등록시 role이 입력에 따라 바뀌게 변경
  src/main/java/com/hotsix/server/proposal/controller/ProposalController.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalRequestBody.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalRequestDto.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalResponseDto.java
  src/main/java/com/hotsix/server/proposal/entity/Proposal.java
  src/main/java/com/hotsix/server/proposal/entity/proposalPorfolio/ProposalFile.java
  src/main/java/com/hotsix/server/proposal/service/ProposalService.java
  src/main/java/com/hotsix/server/user/controller/UserController.java
  src/main/java/com/hotsix/server/user/service/UserService.java
Labels: 🛠️ fix

#35 [fix] 메세지 서비스에 Transaction 어노테이션 추가
  src/main/java/com/hotsix/server/message/controller/MessageController.java
  src/main/java/com/hotsix/server/message/service/MessageService.java
  src/main/java/com/hotsix/server/project/entity/Project.java
  src/main/java/com/hotsix/server/proposal/controller/ProposalController.java
  src/main/java/com/hotsix/server/proposal/entity/ProposalStatus.java
  src/main/java/com/hotsix/server/proposal/service/ProposalService.java
Labels: 🛠️ fix

#36 [feat] SSE통신 및 채팅방 구현
  src/main/java/com/hotsix/server/auth/controller/AuthController.java
  src/main/java/com/hotsix/server/message/controller/ChatRoomController.java
  src/main/java/com/hotsix/server/message/controller/MessageController.java
  src/main/java/com/hotsix/server/message/controller/SseController.java
  src/main/java/com/hotsix/server/message/dto/ChatRoomCreateRequestDto.java
  src/main/java/com/hotsix/server/message/dto/ChatRoomResponseDto.java
  src/main/java/com/hotsix/server/message/dto/MessageRequestDto.java
  src/main/java/com/hotsix/server/message/entity/ChatRoom.java
  src/main/java/com/hotsix/server/message/entity/ChatRoomUser.java
  src/main/java/com/hotsix/server/message/entity/Message.java
  src/main/java/com/hotsix/server/message/exception/ChatRoomErrorCase.java
  src/main/java/com/hotsix/server/message/repository/ChatRoomRepository.java
  src/main/java/com/hotsix/server/message/repository/ChatRoomUserRepository.java
  src/main/java/com/hotsix/server/message/repository/MessageRepository.java
  src/main/java/com/hotsix/server/message/service/ChatRoomService.java
  src/main/java/com/hotsix/server/message/service/MessageService.java
  src/main/java/com/hotsix/server/message/service/SseService.java
  src/main/java/com/hotsix/server/message/sse/ChatRoomEmitterRepository.java
  src/main/java/com/hotsix/server/project/entity/Project.java
  src/main/java/com/hotsix/server/proposal/controller/ProposalController.java
  src/main/java/com/hotsix/server/user/entity/User.java
Labels: 💡 feature

#39 [feat] 제안서 등록시 파일 업로드 기능 구현
  src/main/java/com/hotsix/server/message/controller/ChatRoomController.java
  src/main/java/com/hotsix/server/message/controller/SseController.java
  src/main/java/com/hotsix/server/proposal/controller/ProposalController.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalFileResponseDto.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalRequestBody.java
  src/main/java/com/hotsix/server/proposal/dto/ProposalResponseDto.java
  src/main/java/com/hotsix/server/proposal/entity/Proposal.java
  src/main/java/com/hotsix/server/proposal/entity/ProposalFile.java
  src/main/java/com/hotsix/server/proposal/entity/proposalPorfolio/ProposalFile.java
  src/main/java/com/hotsix/server/proposal/service/ProposalService.java
Labels: 💡 feature

#41 [feat] S3 이미지 업로드 기능 구현
  .github/workflows/dev-ci.yml
  build.gradle
  src/main/java/com/hotsix/server/aws/config/AmazonS3Config.java
  src/main/java/com/hotsix/server/aws/controller/FileUploadController.java
  src/main/java/com/hotsix/server/aws/manager/AmazonS3Manager.java
  src/main/resources/application-ci.yml
Labels: 💡 feature, 🛠️ fix

#42 [chore] 배포용 yml 설정파일 추가
  .gitignore
  src/main/resources/application-prod.yml
Labels: ⚙️ chore
